const cCode = {
  '0': 'AUD-Australian Dollar',
  '1': 'GBP-British Pound',
  '2': 'BRL-Brazilian Real',
  '3': 'BGN-Bulgarian Lev',
  '4': 'CAD-Canadian Dollar',
  '5': 'CNY-Chinese Yuan Renminbi',
  '6': 'HRK-Croatian Kuna',
  '7': 'CYP-Cypriot Pound',
  '8': 'CZK-Czech Koruna',
  '9': 'DKK-Danish Krone',
  '10': 'EEK-Estonian kroon',
  '11': 'EUR-Euro',
  '12': 'HKD-Hong Kong Dollar',
  '13': 'HUF-Hungarian Forint',
  '14': 'ISK-Iceland Krona',
  '15': 'IDR-Indonesian Rupiah',
  '16': 'INR-Indian Rupee',
  '17': 'JPY-Japanese Yen',
  '18': 'KRW-Korean Won',
  '19': 'LVL-Latvian lats',
  '20': 'LTL-Lithuanian Litas',
  '21': 'MYR-Malaysian Ringgit',
  '22': 'MTL-Maltese Lira',
  '23': 'MXN-Mexican peso',
  '24': 'NOK-Norwegian Kroner',
  '25': 'NZD-New Zealand Dollar',
  '26': 'PHP-Philippine Peso',
  '27': 'PLN-Polish Zloty',
  '28': 'ROL-Romanian Old Leu',
  '29': 'RON-Romanian New Leu',
  '30': 'RUB-Russian Rouble',
  '31': 'SGD-Singapore Dollar',
  '32': 'SEK-Swedish krona',
  '33': 'SKK-Slovak Koruna',
  '34': 'SIT-Slovenian Tolar',
  '35': 'ZAR-South African Rand',
  '36': 'CHF-Swiss Franc',
  '37': 'THB-Thai Baht',
  '38': 'TRL-Turkish Old Lira',
  '39': 'TRY-Turkish Lira',
  '40': 'USD-US Dollar',
  '41': 'AED-Utd. Arab Emir. Dirham',
};

const cCountry = {
  'AUD-Australian Dollar': '0',
  'GBP-British Pound': '1',
  'BRL-Brazilian Real': '2',
  'BGN-Bulgarian Lev': '3',
  'CAD-Canadian Dollar': '4',
  'CNY-Chinese Yuan Renminbi': '5',
  'HRK-Croatian Kuna': '6',
  'CYP-Cypriot Pound': '7',
  'CZK-Czech Koruna': '8',
  'DKK-Danish Krone': '9',
  'EEK-Estonian kroon': '10',
  'EUR-Euro': '11',
  'HKD-Hong Kong Dollar': '12',
  'HUF-Hungarian Forint': '13',
  'ISK-Iceland Krona': '14',
  'IDR-Indonesian Rupiah': '15',
  'INR-Indian Rupee': '16',
  'JPY-Japanese Yen': '17',
  'KRW-Korean Won': '18',
  'LVL-Latvian lats': '19',
  'LTL-Lithuanian Litas': '20',
  'MYR-Malaysian Ringgit': '21',
  'MTL-Maltese Lira': '22',
  'MXN-Mexican peso': '23',
  'NOK-Norwegian Kroner': '24',
  'NZD-New Zealand Dollar': '25',
  'PHP-Philippine Peso': '26',
  'PLN-Polish Zloty': '27',
  'ROL-Romanian Old Leu': '28',
  'RON-Romanian New Leu': '29',
  'RUB-Russian Rouble': '30',
  'SGD-Singapore Dollar': '31',
  'SEK-Swedish krona': '32',
  'SKK-Slovak Koruna': '33',
  'SIT-Slovenian Tolar': '34',
  'ZAR-South African Rand': '35',
  'CHF-Swiss Franc': '36',
  'THB-Thai Baht': '37',
  'TRL-Turkish Old Lira': '38',
  'TRY-Turkish Lira': '39',
  'USD-US Dollar': '40',
  'AED-Utd. Arab Emir. Dirham': '41',
};
